### ISSUE TITLE
inference of PointerGenerator 

### ISSUE THREAD

**Issue by BD-MF** [jiminsun/pointer-generator#1]
Hello, there are many parameters of inference in PointerGenerator. The first dimension is multiplied by a batch_size, which is different from the previous model dimension. Why?

Then what does the K in inference mean?

**Comment by jiminsun** [comment]
Hi,
First of all, the K used during inference indicates the beam size for beam search.
During inference, we keep track of the top-K hypotheses per sample in the batch at every timestep.
Therefore, we initially generate K * (batch_size) hypotheses.
Hope this helps and let me know if there are any additional questions.
